name: build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

      # required by guardian/actions-riff-raff
      id-token: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '11'
        cache: 'sbt'

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: CI
      working-directory: cdk
      run: |
        npm ci
        npm run lint
        npm test
        npm run synth

    - name: Build and Test project, Assemble jar, copy to root dir
      run: |
        sbt clean compile test assembly
        cp target/scala*/elastic-search-monitor.jar ./elastic-search-monitor.jar

    - name: Upload to riff-raff
      uses: guardian/actions-riff-raff@v4
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        configPath: cdk/cdk.out/riff-raff.yaml
        projectName: elastic-search-monitor
        buildNumberOffset: 99
        contentDirectories: |
          elastic-search-monitor:
          - elastic-search-monitor.jar
          cdk.out:
          - cdk/cdk.out/ElasticSearchMonitor-PROD.template.json
