name: build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
    - name: run number with offset
      env:
        NUM: ${{ github.run_number }}
      run: echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$((10000+$NUM))" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Setup SBT environment
      uses: Jtalk/setup-sbt@v2
      with:
        version: 1.5.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: CI
      working-directory: cdk
      run: |
        npm i -g yarn
        yarn install --frozen-lockfile
        yarn lint
        yarn test
        yarn synth
        mv "cdk.out/riff-raff.yaml" ../riff-raff.yaml
    - name: AWS Auth
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        aws-region: eu-west-1
    - name: Build and Test project, and Assemble jar
      run: |
        sbt clean compile test assembly
        cp target/scala*/elastic-search-monitor.jar ./elastic-search-monitor.jar
    - name: Upload to riff-raff
      uses: guardian/actions-riff-raff@v2
      with:
        app: elastic-search-monitor
        configPath: riff-raff.yaml
        projectName: elastic-search-monitor
        buildNumberOffset: 10000
        contentDirectories: |
          elastic-search-monitor:
          - elastic-search-monitor.jar
          cdk.out:
          - cdk/cdk.out/ElasticSearchMonitor-PROD.template.json
